name: CIC

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
   	  - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: 'www-staging.nowrx.com'
          REMOTE_USER: 'bitnami'
          REMOTE_PORT: '2222'
          SOURCE: "./Users/barnettj7/Sites/wp-valet/wp-content/themes/NowRx/*"
          TARGET: '~/Sites/wp-valet/wp-content/themes/NowRx'