on: [push]

jobs:
    deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
        uses: actions/checkout@v2
        - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: 'bitnami'
            server: 'www-staging.nowrx.com'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            local_path: '/Users/barnettj7/Sites/wp-valet/wp-content/themes/NowRx/*'
            remote_path: '/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/nowrx'
            sftpArgs: '-o ConnectTimeout=5'