name: CIc

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'bitnami'
          server: 'www-staging.nowrx.com'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './Users/barnettj7/Sites/wp-valet/wp-content/themes/NowRx/*'
          remote_path: './opt/bitnami/apps/wordpress/htdocs/wp-content/themes/nowrx'
          sftp_only: true
          args: '-o ConnectTimeout=10'