name: CI-SFTP

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: bitnami
        server: www-staging.nowrx.com
        port: 22 # default is 22
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: /Users/barnettj7/Sites/wp-valet/wp-content/themes/NowRx
          remote_path: /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/nowrx

        # sftp args
        args: '-o ConnectTimeout=5'
